### ISSUE TITLE
Grafana dashboards in cnv-prod are not updated after changing .json stored in thoth-application

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#1004]
**Describe the bug**
Grafana dashboards in cnv-prod are not updated after changing .json stored in thoth-application

**To Reproduce**
1.Check stage dashboard: https://grafana.datahub.redhat.com/dashboard/db/thoth-knowledge-graph-content-metrics?refresh=30s&orgId=1
2. Check prod dashboard: https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/dd5ddeda417f2083b1b0526b222609dfcf1145be/thoth-knowledge-graph-content-metrics?orgId=1&refresh=30s

**Expected behavior**
When a generic dashboard.json file is changed, grafana-operator should redeploy the dashboard.

**Screenshots**

**Additional context**
cc @4n4nd @hemajv

**Comment by harshad16** [comment]
Thanks for opening the issue.
This is happening as we are making changes in the grafana dashboard JSON (which reside in thoth-application) and point the URL of that to the monitoring app(which reside opf/apps) . The argocd is looking at the monitoring app and syncing it, as there is no change in the monitoring app itself, argocd doesn't re-sync.
anyhow, what we want is to have the Grafana operator to pull in the new changes based on the URL. 
working with the operate-first team to come up with a plan on how to proceed with such changes in the future. 
cc: @4n4nd

**Comment by 4n4nd** [comment]
The issue is, when you set up a dashboard with a remote link, the operator does not know if the dashboard has been updated. This is because the dashboard json is downloaded once by the operator when the dashboard CR is created.

The current suggested solution would be to add an annotation (like version number) to the Grafana Dashboard CRs ([link](https://github.com/operate-first/apps/blob/master/odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml#L3)) and update the annotations in order for the operator to download the new dashboard json

**Comment by pacospace** [comment]
> The issue is, when you set up a dashboard with a remote link, the operator does not know if the dashboard has been updated. This is because the dashboard json is downloaded once by the operator when the dashboard CR is created.
> 
> The current suggested solution would be to add an annotation (like version number) to the Grafana Dashboard CRs ([link](https://github.com/operate-first/apps/blob/master/odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml#L3)) and update the annotations in order for the operator to download the new dashboard json

So the workflow is to send two PRs:

1. send a PR to change your dashboard
2. send a PR to change the annotation using for example the dashboard version number in the CR.

Thanks @4n4nd!

**Comment by harshad16** [comment]
yes correct , those would be the steps to update the dashboards.

**Comment by goern** [comment]
is this actively being worked on?

/lifecycle stale

**Comment by pacospace** [comment]
> is this actively being worked on?
> 
> /lifecycle stale

We can conclude it maybe adding some docs on how to avoid this issue, @harshad16 wdyt?

**Comment by harshad16** [comment]
yes we can add some docs for this update.
/lifecycle active

**Comment by goern** [comment]
is this actively being worked on?

/priority important-longterm

**Comment by pacospace** [comment]
> is this actively being worked on?
> 
> /priority important-longterm

@harshad16 already took care. We just miss some docs to close this issue.

**Comment by goern** [comment]
@4n4nd could you please turn this into a document? I don't get what I need to do (and where) to get the dashboards changed...

**Comment by 4n4nd** [comment]
@goern https://github.com/operate-first/apps/issues/803

**Comment by pacospace** [comment]
> what is the root blocker of this issue? how can we remove it?

Cc @4n4nd

**Comment by VannTen** [comment]
Hum...

If I understand correctly, the issue is that we're using a remote url
and somehow feed it to the grafana-operator, which does not update since
the manifest do not change (only the url content).

I don't think we should manage our dashboard with json on a remote url
at the grafana-operator level. In my view, if we're doing Gitops, the
gitops process/handler is responsible for "reifying" git + whatever into
immutable manifests.

Couldn't we use either raw json or a configMap create from the url at
bundle/git sync time ? Is there context making this not possible /
practical ?

From the grafana-operator doc:

## Dashboard properties

To get a quick overview of the GrafanaDashboard you can also look at the [API docs](api.md).
The following properties are accepted in the `spec`:

* *json*: Raw json string with the dashboard contents. Check
  the [official documentation](https://grafana.com/docs/reference/dashboard/#dashboard-json).
* *gzipJson*: Raw json that has been gzipped, and then base64-encoded, similar to a Secret.
* *jsonnet*: Jsonnet source. The [Grafonnet](https://grafana.github.io/grafonnet-lib/) library is made available
  automatically and can be imported.
* *url*: Url address to download a json or jsonnet string with the dashboard contents.
  * ***Warning***: If both url and json are specified then the json field will be cleared if the downloaded content is identical.
  * *The dashboard fetch priority by parameter is: url > configmap > json > jsonnet.*
* *plugins*: A list of plugins required by the dashboard. They will be installed by the operator if not already present.
* *datasources*: A list of datasources to be used as inputs. See [datasource inputs](#datasource-inputs).
* *configMapRef*: Import dashboards from config maps. See [config map references](#config-map-references).
* *gzipConfigMapRef*: Same as `configMapRef`, but the referenced field is decoded like `gzipJson` is.
* *customFolderName*: Assign this dashboard to a custom folder, if no folder with this name exists on the instance, then
  a new one will be created.
  * *Note*: Folders with custom names are not managed by the operator, by purposeful design they won't be deleted when
      empty, deletion for these requires manual intervention.

**Comment by harshad16** [comment]
Thanks for your thoughts @VannTen 
we could go with configmap method, we didn't go with that initially as configmap would be needed to be deployed to the same namespace, and operate-first would have to track what's getting deployed on their monitoring namespace.
with the URL method, users can still keep the content on their end instead of keeping it on operate-first.


Anyhow, the great news is the issue is fixed.
with grafana operator implementation of a refresh. Now URLs are pulled in after the cache limit.
This is fix: https://github.com/grafana-operator/grafana-operator/issues/440#issuecomment-1283718122
Already the effect can be seen in the operate-first.

Thanks @4n4nd for the issue in upstream.
closing this issue as the problem is resolved.
