### ISSUE TITLE
Advise fails on khemenu deployment

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1199]
**Describe the bug**

```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT DISTINCT depends_on.extra AS depends_on_extra, python_package_version_entity.package_name AS python_package_version_entity_package_name, python_package_version_entity.package_version AS python_package_version_entity_package_version 
FROM python_package_version JOIN python_package_index ON python_package_index.id = python_package_version.python_package_index_id JOIN depends_on ON python_package_version.id = depends_on.version_id JOIN python_package_version_entity ON python_package_version_entity.id = depends_on.entity_id 
WHERE python_package_version.package_name = %(package_name_1)s AND python_package_version.package_version = %(package_version_1)s AND python_package_version.os_name = %(os_name_1)s AND python_package_version.os_version = %(os_version_1)s AND python_package_version.python_version = %(python_version_1)s AND python_package_version.is_missing = false AND python_package_index.url = %(url_1)s AND depends_on.extra IS NULL AND depends_on.marker_evaluation_result = true]
[parameters: {'package_name_1': 'flask', 'package_version_1': '1.1.2', 'os_name_1': 'rhel', 'os_version_1': '8', 'python_version_1': '3.6', 'url_1': 'https://pypi.org/simple'}]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
```

**To Reproduce**
1. Ask for an advise on khemenu.thoth-station.ninja
4. See an error

**Expected behavior**

Advise should succeed.

**Comment by goern** [comment]
@tumido could you have a look at out well our Postgres server in thoth-graph-prod feels? Or is that something for @harshad16 ?

**Comment by tumido** [comment]
Not sure what to look for. The DB pod was last restarted on 2021-04-19, since then it didn't report any errors, Kibana and Loki are both silent on that namespace. It seems we may be missing some service/pod monitors there @harshad16 @4n4nd, can you please take a look what we can do to get proper metrics on that namespace?

Thoth dasboards for this DB seems silent as well:
https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/5f2a5d7b1356c0c8ce4277724c131ed1beac864f/thoth-postgresql-metrics?orgId=1&refresh=30s&from=now-1h&to=now
![image](https://user-images.githubusercontent.com/7453394/116085486-2672ca00-a69f-11eb-8747-ea1383d74b85.png)


Other than that, the DB pod itself seems healthy and since its restart it didn't report any errors. No idea what is going on there. Network is not reporting any dropped packets or connections:
![image](https://user-images.githubusercontent.com/7453394/116085847-87020700-a69f-11eb-9684-4bf047b4664a.png)

**Comment by fridex** [comment]
Looks like this was a hiccup, the service is up and operational now. I saw such issues when the database was unreachable (probably pgbouncer or pg network issue).

/close
