### ISSUE TITLE
ImageStreamTag in core should be updated once new image on quay is created.

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#120]

**Comment by harshad16** [comment]
absolutely, the image stream tag should have been updated automatically by ci bot.
it failed to do that earlier due to misconfiguration of the contextpath : https://github.com/thoth-station/investigator/blob/966405670aab13c32991d02bca76948b2a6156a5/.aicoe-ci.yaml#L15
it should be pointing to `core/overlays/test/imagestreamtags.yaml` .
will send in the fix.
