### ISSUE TITLE
Stage data keep multiple same solver rules

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#1939]
**Describe the bug**

The current dataset computed in stage environment has multiple solver rules entries of the same type. This was probably caused by the initialization triggered multiple times. 

The solver rules creation logic should not create multiple entries of the same type.

**Comment by goern** [comment]
@fridex This needs to be solved in init-job?

**Comment by harshad16** [comment]
This issue was solved by performing the following procedure:
- Pause ingestion components like graph-refresh, package-releases, cve-update, etc to stop the update of the association of solvers rules with newly ingested packages.
- Truncate the tables: **PythonPackageVersionEntityRule** , **PythonPackageVersionEntityRulesAssociation**
This operation is done to remove all the solvers rules and their associations with packages.
- Run the init-job initializer for only solver rules configuration.
- Resume all ingestion components to fill up the associations with rules.


This seems to be successfully done.
closing the issue
please feel free to open and describe what went missing.
