### ISSUE TITLE
Kebechet github installation table managers columns are all false

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#2165]
**Describe the bug**
Kebechet github installation table managers are all false

**To Reproduce**
1. pgweb and check Kebechet GitHubInstallation table

**Expected behavior**
managers are updated together with software stacks used for each repo

**Screenshots**

**Additional context**
Related-To: https://github.com/thoth-station/core/issues/322

**Comment by pacospace** [comment]
@KPostOffice when do we update that table with those information?

**Comment by KPostOffice** [comment]
The issue is pretty simple actually. The update-keb-installation workflow step was only enabled in the test overlay to start and we never added it to the base overlay so it is not being updated in production or stage.

See here:
https://github.com/thoth-station/thoth-application/blob/4848c535257b9bb2de29a89f14d14d574a4e0021/kebechet/overlays/test/kebechet.yaml#L115
