### ISSUE TITLE
Managing data across deployments

### ISSUE THREAD

**Issue by fridex** [thoth-station/thoth-application#2282]
**Is your feature request related to a problem? Please describe.**

Let's check and document how we could manage data in multiple deployments.

**Describe the solution you'd like**

- [x] have document-sync-job deployed in the stage environment and let it sync data to the required deployments

- [x] let's see how document-sync-job works in deployments to automatically manage data
  - [x] there might be needed an optimization to sync only data computed since the last sync given the volume of data
  - [x] the sync should be a background job so that it requires minimal human effort and data are ready on each release
  - [x] have metrics exposed https://github.com/thoth-station/document-sync-job/pull/6

The bottom two checklist would be take care by: https://github.com/thoth-station/thoth-application/issues/2513
- [ ] check if we can automate PostgreSQL dumps
- [ ] document how we would like to manage data in deployments
  - [ ] how stage data are populated, what needs to be done automatically and what is manual

Related: https://github.com/thoth-station/thoth-application/issues/2268

**Comment by harshad16** [comment]
Data migration based on the postgresql db dumps: https://github.com/thoth-station/thoth-application/issues/2216
/triage accepted
/priority important-soon

**Comment by harshad16** [comment]
Component [document-sync-job](https://github.com/thoth-station/document-sync-job) was created to accommodate the needs. 
The deployment of the document-sync-job is created via the following issues: 
- https://github.com/thoth-station/thoth-application/pull/2286
- https://github.com/thoth-station/thoth-application/pull/2319
- https://github.com/thoth-station/thoth-application/pull/2323
- https://github.com/thoth-station/thoth-application/pull/2324
- https://github.com/thoth-station/thoth-application/pull/2327
- https://github.com/thoth-station/thoth-application/pull/2332
- https://github.com/thoth-station/thoth-application/pull/2476

This issue is worked and completed.
Thanks for all the efforts @fridex :100:
