### ISSUE TITLE
error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1"

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/thoth-application#2333]
**Describe the bug**
There was a recent update for the cronjob apiversion from `v1beta1` to `v1` https://github.com/thoth-station/thoth-application/commit/f87bb38b849d9830b707d9fa890df26f9df15623#diff-c9df3191eada55b0b3ed54130f15f338bd5aede95e25ada296b1b4c1c590a00e, which was however reverted https://github.com/thoth-station/thoth-application/commit/3b4fdb803de586b1b5cd4d927e1a9b2cddf575d4#diff-c9df3191eada55b0b3ed54130f15f338bd5aede95e25ada296b1b4c1c590a00e

Now, when creating a job out of cronjob, error occurs.
There is no documentation at the referenced link from cli k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28

**To Reproduce**
```
 oc create job --from=cronjob/mi-scheduler-kebechet-analyse mi-keb-analyse-tue
```
**Expected behavior**

**LOGS**
```
error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
```

/kind bug

**Comment by xtuchyna** [comment]
updating to `v1` does not work, too
`error: from must be an existing cronjob: no kind "CronJob" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"`

**Comment by harshad16** [comment]
The question is correct and very relevant.
However, it is an issue in a cluster.
As the openshift version updated, they have moved to the version `v1` manifest. [Reference](https://docs.openshift.com/container-platform/4.8/rest_api/workloads_apis/cronjob-batch-v1.html)

However, the cluster infra we are in, don't have this CRD updated.
So technically we are still using `batch/v1beta1`.
one can check this by trying to create a cronjob in the cluster.
https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-test-core/cronjobs/~new

and since the cronjob is at version `[batch/v1beta1](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-test-core/cronjobs/~new)` and job is moved to version `[v1](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-test-core/jobs/~new)` 
the ` oc create job --from=cronjob/<name> <job-name>` wouldn't work.

Solution:
we would have to wait for infra team to update the CRDs

Alternative:
As I reckon this is for testing, we have an alternate, please extract `job template` from cronjob `spec`
and create a job based on the job template via CLI or [UI](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/thoth-test-core/jobs/~new).

**Comment by goern** [comment]
/priority important-soon

is someone working on this?

**Comment by xtuchyna** [comment]
> where are you running this cronjob? in smaug the cronjob work with `apiVersion: batch/v1beta1

@pacospace @harshad16 so there is no issue within smaug then? I thought that this happened in every cluster, as discussed with harshad. Should we move `mi` there ( https://github.com/thoth-station/thoth-application/pull/2358 ) ?
