### ISSUE TITLE
Verify if the auto increment of entries in PGSQL is scalable 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2534]
The auto-increment of entries in PGSQL is set, with purge jobs and sync jobs running for data ingestion, we should ensure that the auto_increment of entries in PGSQL can scale and live up to project thoth requirements.

**Comment by VannTen** [comment]
How would we define scalable in that context ?

It's pretty unlikely we're going to bring pgsql to its knees because of the auto_increment of PL (this is about PK).
If we really have lots of stuff in the tables we  switch to 64-bit int (`bigserial` I think ?)

Besides benchmarks, what information are we after here ?  (If it's indeed benchmarks, not sure that `good-first-issue` apply)

**Comment by VannTen** [comment]
If we keep this (not sure we should), we should have a concrete requirements to test against PostgresSQL, and the acceptance critera would be something like:
- [ ] benchmarked PostgresSQL with requirements X .

/needs-triage
