### ISSUE TITLE
The `activeDeadlineSeconds` set for solver pods does not allow them to finish

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thoth-application#2569]
**Describe the bug**

Solvers scheduled for some packages are terminated before they have finished because of the `activeDeadlineSeconds` being set to 900s. We should consider increasing this deadline to see if the solvers finish successfully.

**To Reproduce**

Schedule a solver for a package in the management API and see the pod event specifying that the solver was terminated because the `activeDeadlineSeconds` was exceeded.
Example: package `copr` with version specifier `"*"` for `fedora-35-py310`.

**Expected behavior**

Solvers finish on time.

**Comment by fridex** [comment]
+1

In some cases, we run 2 solvers if one fails due to resource allocation. See https://github.com/thoth-station/thoth-application/issues/1892 and https://github.com/thoth-station/thoth-application/pull/1894. It might be good idea to keep the first activeDeadlineSeconds set to 900 and let the second one (`solve-res` with more resources) have more CPU time allocated by increasing activeDeadlineSeconds:

https://github.com/thoth-station/thoth-application/blob/8c5587a59b667e19e3176cbff3c27eca09417b92/solver/base/argo-workflows/solver-template.yaml#L194

**Comment by mayaCostantini** [comment]
Sounds good, thanks for the explanation :+1: Opening a PR with the change soon.

**Comment by fridex** [comment]
Just reasoning here - the first solver tries to solve packages "quick and low resources". If that fails, more resources (mem, CPU, CPU time) are allocated. The first solver should solve most of the Python packages that do not need any compilation and are relatively small. This is the case for most of the packages (these numbers are present in the SLI/SLO metrics).

**Comment by mayaCostantini** [comment]
Solvers are now running successfully, closing this issue.
Closed by https://github.com/thoth-station/thoth-application/pull/2570
