### ISSUE TITLE
Thoth is not learning

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#718]
![Screenshot from 2020-12-15 10-20-33](https://user-images.githubusercontent.com/27498679/102195696-37285d80-3ebf-11eb-9590-bea381a4b66c.png)

**Comment by goern** [comment]
@pacospace will you work on this? did you figure out a root cause? 

/label sig/devops
/label sig/knowledge-graph
/king bug
/priority critical-urgent

**Comment by pacospace** [comment]
> @pacospace will you work on this? did you figure out a root cause?
> 
> /label sig/devops
> /label sig/knowledge-graph
> /king bug
> /priority critical-urgent

I'm still trying to identify the root cause. I miss the endpoints for Kafka and kafdrop to check what is the status there. I don't see issues in ocp4.

**Comment by pacospace** [comment]
> > @pacospace will you work on this? did you figure out a root cause?
> > /label sig/devops
> > /label sig/knowledge-graph
> > /king bug
> > /priority critical-urgent
> 
> I'm still trying to identify the root cause. I miss the endpoints for Kafka and kafdrop to check what is the status there. I don't see issues in ocp4. @goern

I might be the incident happening in PSI still not solved.

**Comment by harshad16** [comment]
I couldnt get to message earlier about this, anyhow the nodes on the ocp cluster are tainted, we cant use the cluster as of now.
the psi team had instructed earlier when similar issue occurred , to migrate on ocp4 clusters.

**Comment by harshad16** [comment]
ocp cluster is facing the dns network issue which we also faced in the ocp 4.5 cluster. 
due to this, pods are having issue scheduling.

**Comment by harshad16** [comment]
This was fixed with help of the infra team, some details are defined in the following tickets
https://redhat.service-now.com/surl.do?n=RITM0808948
https://redhat.service-now.com/surl.do?n=RITM0801568

All these happened during the RedHat break, the work was done effectively in getting back the system to normal.
The system ran with small hiccups during the last few weeks of the year, however, the system was able to do valuable work.
closing this issue. Please re-open if found the issue again or need more information.
