### ISSUE TITLE
review dashboards

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#938]
Some of the Grafana Dashboards seem to have problems getting the right data, see https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/860ad3c2506d4744729adba986fdec914b3b4b75/thoth-service-metrics?orgId=1&refresh=30s

**Comment by pacospace** [comment]
Some metrics are not visualized, either because source of data is wrong (it should be Thoth station) or endpoint which target stage.

- https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/a30fccbb3c61cc644827f080c68c460d2132bc4a/thoth-sli-slo?orgId=1&refresh=30s

- https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/860ad3c2506d4744729adba986fdec914b3b4b75/thoth-service-metrics?orgId=1&refresh=30s

We need to update json files in thoth-application

**Comment by pacospace** [comment]
Add also up metrics for User-API to dashboard to track availability.

**Comment by pacospace** [comment]
Corrected issues for labels in some metrics. 

> Some of the Grafana Dashboards seem to have problems getting the right data, see https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/860ad3c2506d4744729adba986fdec914b3b4b75/thoth-service-metrics?orgId=1&refresh=30s

The json dashboard in thoth application actually is correct, not sure why the one in cnv-prod is not synced based on that overlay. cc @harshad16

**Comment by pacospace** [comment]
it was an issue from argoCD that has been solved: https://github.com/thoth-station/thoth-application/issues/1004. we can close this issue
